version: '3'

services:
  db:
    image: mysql
    environment:
     - DB_HOST=mysql
     - MYSQL_DATABASE='whatsdownDB'
     - MYSQL_USER='whatsdown'
     - MYSQL_PASSWORD='#W4lepsze'     
     - MYSQL_ROOT_PASSWORD='qwerty'
    ports:
     - "3306"
    networks:
     - backend
  web:
    build: .
    command: flask run
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
     - backend
networks:
    backend:
