"""improved m2m relations

Revision ID: 089b537d203e
Revises: e90f2e9a94ab
Create Date: 2019-11-20 00:32:10.110458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '089b537d203e'
down_revision = 'e90f2e9a94ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('priest_temple', sa.Column('priest_last_name', sa.Integer(), nullable=True))
    op.drop_constraint('priest_temple_ibfk_1', 'priest_temple', type_='foreignkey')
    op.create_foreign_key(None, 'priest_temple', 'priest', ['priest_last_name'], ['last_name'])
    op.drop_column('priest_temple', 'priest_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('priest_temple', sa.Column('priest_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'priest_temple', type_='foreignkey')
    op.create_foreign_key('priest_temple_ibfk_1', 'priest_temple', 'priest', ['priest_id'], ['id'])
    op.drop_column('priest_temple', 'priest_last_name')
    # ### end Alembic commands ###
