"""fixed funeral home fk

Revision ID: 412f34e67a2a
Revises: c5fabcc75dc2
Create Date: 2019-12-10 19:33:34.213260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '412f34e67a2a'
down_revision = 'c5fabcc75dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funeral', 'funeral_home_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('funeral_ibfk_1', 'funeral', type_='foreignkey')
    op.create_foreign_key(None, 'funeral', 'funeral_home', ['funeral_home_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('quarter_ibfk_2', 'quarter', type_='foreignkey')
    op.create_foreign_key(None, 'quarter', 'tombstone', ['tombstone_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quarter', type_='foreignkey')
    op.create_foreign_key('quarter_ibfk_2', 'quarter', 'tombstone', ['tombstone_id'], ['id'])
    op.drop_constraint(None, 'funeral', type_='foreignkey')
    op.create_foreign_key('funeral_ibfk_1', 'funeral', 'funeral_home', ['funeral_home_id'], ['id'])
    op.alter_column('funeral', 'funeral_home_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
