"""added autoclear

Revision ID: 43dc569f02a6
Revises: ee1555d09cdf
Create Date: 2019-11-19 20:24:27.082889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43dc569f02a6'
down_revision = 'ee1555d09cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('priest_temple', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('priest_temple', 'id')
    # ### end Alembic commands ###
