"""fixed admin, added all tables

Revision ID: 5b81b9815043
Revises: a92f616bae9b
Create Date: 2019-11-01 23:49:13.253220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b81b9815043'
down_revision = 'a92f616bae9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cemetery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voivodeship', sa.Text(), nullable=True),
    sa.Column('county', sa.Text(), nullable=True),
    sa.Column('locality', sa.Text(), nullable=True),
    sa.Column('street', sa.Text(), nullable=True),
    sa.Column('faith', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('container',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_of_container', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.Text(), nullable=True),
    sa.Column('material', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funeral_home',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('voivodeship', sa.Text(), nullable=True),
    sa.Column('county', sa.Text(), nullable=True),
    sa.Column('locality', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('login', sa.String(length=30), nullable=True),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('name')
    )
    op.create_table('outfit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_of_clothing', sa.Text(), nullable=True),
    sa.Column('size', sa.Text(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('priest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('religion', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temple',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voivodeship', sa.Text(), nullable=True),
    sa.Column('county', sa.Text(), nullable=True),
    sa.Column('locality', sa.Text(), nullable=True),
    sa.Column('religion', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tombstone',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manufacturer', sa.Text(), nullable=True),
    sa.Column('material', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funeral',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('total_price', sa.Integer(), nullable=True),
    sa.Column('funeral_home_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['funeral_home_id'], ['funeral_home.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('priest_temple',
    sa.Column('priest_id', sa.Integer(), nullable=True),
    sa.Column('temple_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['priest_id'], ['priest.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temple.id'], )
    )
    op.create_table('quarter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('x_coord', sa.Integer(), nullable=True),
    sa.Column('y_coord', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('cemetery_id', sa.Integer(), nullable=False),
    sa.Column('tombstone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cemetery_id'], ['cemetery.id'], ),
    sa.ForeignKeyConstraint(['tombstone_id'], ['tombstone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buried',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('death_date', sa.DateTime(), nullable=True),
    sa.Column('cause_of_death', sa.Text(), nullable=True),
    sa.Column('outfit_id', sa.Integer(), nullable=True),
    sa.Column('container_id', sa.Integer(), nullable=True),
    sa.Column('quarter_id', sa.Integer(), nullable=False),
    sa.Column('funeral_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['container.id'], ),
    sa.ForeignKeyConstraint(['funeral_id'], ['funeral.id'], ),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfit.id'], ),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('administrator', sa.Column('login', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'administrator', ['login'])
    op.drop_column('administrator', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrator', sa.Column('name', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'administrator', type_='unique')
    op.drop_column('administrator', 'login')
    op.drop_table('buried')
    op.drop_table('quarter')
    op.drop_table('priest_temple')
    op.drop_table('funeral')
    op.drop_table('tombstone')
    op.drop_table('temple')
    op.drop_table('priest')
    op.drop_table('outfit')
    op.drop_table('funeral_home')
    op.drop_table('container')
    op.drop_table('cemetery')
    # ### end Alembic commands ###
