"""added association table

Revision ID: 6a780b4dabe1
Revises: 5b81b9815043
Create Date: 2019-11-02 11:18:40.213157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a780b4dabe1'
down_revision = '5b81b9815043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('administrator', 'login',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('funeral_home', 'login',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funeral_home', 'login',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('administrator', 'login',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###
