"""added removal funeral without buried and added single-parent fields

Revision ID: 7450f0ee122b
Revises: 
Create Date: 2019-11-25 21:46:26.210292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7450f0ee122b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('cemetery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voivodeship', sa.Text(), nullable=True),
    sa.Column('county', sa.Text(), nullable=True),
    sa.Column('locality', sa.Text(), nullable=True),
    sa.Column('street', sa.Text(), nullable=True),
    sa.Column('faith', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('container',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_of_container', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.Text(), nullable=True),
    sa.Column('material', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funeral_home',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('voivodeship', sa.Text(), nullable=True),
    sa.Column('county', sa.Text(), nullable=True),
    sa.Column('locality', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('login', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('name')
    )
    op.create_table('outfit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_of_clothing', sa.Text(), nullable=True),
    sa.Column('size', sa.Text(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('priest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('religion', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temple',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voivodeship', sa.Text(), nullable=True),
    sa.Column('county', sa.Text(), nullable=True),
    sa.Column('locality', sa.Text(), nullable=True),
    sa.Column('religion', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tombstone',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manufacturer', sa.Text(), nullable=True),
    sa.Column('material', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('priest_temple',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('priest_id', sa.Integer(), nullable=True),
    sa.Column('temple_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['priest_id'], ['priest.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temple.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quarter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('x_coord', sa.Integer(), nullable=True),
    sa.Column('y_coord', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('cemetery_id', sa.Integer(), nullable=False),
    sa.Column('tombstone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cemetery_id'], ['cemetery.id'], ),
    sa.ForeignKeyConstraint(['tombstone_id'], ['tombstone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funeral',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('funeral_home_id', sa.Integer(), nullable=False),
    sa.Column('priest_temple_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['funeral_home_id'], ['funeral_home.id'], ),
    sa.ForeignKeyConstraint(['priest_temple_id'], ['priest_temple.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buried',
    sa.Column('PESEL', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('death_date', sa.Date(), nullable=True),
    sa.Column('cause_of_death', sa.Text(), nullable=True),
    sa.Column('outfit_id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('quarter_id', sa.Integer(), nullable=False),
    sa.Column('funeral_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['container.id'], ),
    sa.ForeignKeyConstraint(['funeral_id'], ['funeral.id'], ),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfit.id'], ),
    sa.ForeignKeyConstraint(['quarter_id'], ['quarter.id'], ),
    sa.PrimaryKeyConstraint('PESEL')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buried')
    op.drop_table('funeral')
    op.drop_table('quarter')
    op.drop_table('priest_temple')
    op.drop_table('tombstone')
    op.drop_table('temple')
    op.drop_table('priest')
    op.drop_table('outfit')
    op.drop_table('funeral_home')
    op.drop_table('container')
    op.drop_table('cemetery')
    op.drop_table('administrator')
    # ### end Alembic commands ###
