"""Added admin authorisation field

Revision ID: 7c4a5c87d104
Revises: 6a780b4dabe1
Create Date: 2019-11-05 19:00:52.609912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4a5c87d104'
down_revision = '6a780b4dabe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrator', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('funeral_home', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funeral_home', 'is_admin')
    op.drop_column('administrator', 'is_admin')
    # ### end Alembic commands ###
