"""Changed funeral and funeral_home relation

Revision ID: 97b2f4e48fb5
Revises: 8fd5af156187
Create Date: 2019-11-29 18:03:40.534673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97b2f4e48fb5'
down_revision = '8fd5af156187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funeral', 'funeral_home_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funeral', 'funeral_home_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
