"""improved m2m relations

Revision ID: e90f2e9a94ab
Revises: 62c057b0b2b0
Create Date: 2019-11-19 23:42:52.345518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90f2e9a94ab'
down_revision = '62c057b0b2b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priest_temple',
    sa.Column('priest_id', sa.Integer(), nullable=True),
    sa.Column('temple_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['priest_id'], ['priest.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temple.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('funeral', sa.Column('priest_temple_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'funeral', 'priest_temple', ['priest_temple_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'funeral', type_='foreignkey')
    op.drop_column('funeral', 'priest_temple_id')
    op.drop_table('priest_temple')
    # ### end Alembic commands ###
